title: BorCast
email: borafirlangec@gmail.com
description: "Borfirbora durmuyor, PodCast işine de el atıyor. Teknolojik gelişmelerden günlük yaşam muhabbetlerine, oyunlardan edebi eserlere varan geniş yelpazede hem tekli hem konuklu sohbetler gerçekleştiriyor, eğitimler veriyor. Hem eğlendiriyor, hem bilgilendiriyor hem de bildiklerini aktarıyor. Dinleyelim bakalım Borfirbora, BorCast ile bizlere neler neler anlatıyor!"
subtitle: "Bir Bora FIRLANGEÇ söyleşisi"
lang: tr-tr
author: Bora FIRLANGEÇ
copyright: "&#xA9; 2020"
baseurl: "/borcast" # the subpath of your site, e.g. /blog
url: "https://borfirbora.com" # the base hostname & protocol for your site
twitter_username: borfirbora
github_username: borfirbora

permalink: /bolum/:title.html

#Timezone
timezone: Europe/Istanbul

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']