title: Zorunlu PodCast
email: ozguraltinok83@gmail.com
description: "eğitici ve öğretici kişisel podcast serime hoşgeldiniz."
subtitle: "Kendisi sorunlu, dinlenmesi zorunlu podcast"
lang: tr-tr
author: Özgür ALTINOK
copyright: "&#xA9; 2020"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zorcast.github.io" # the base hostname & protocol for your site
twitter_username: ozguraltinok1
github_username: zorcast

permalink: /:title.html

#Timezone
timezone: Europe/Istanbul

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

paginate: 10

plugins:
  - jekyll-paginate

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']